-keep class com.google.gson.**
-optimizationpasses 5
-dontskipnonpubliclibraryclassmembers
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-obfuscationdictionary tomask.txt
-classobfuscationdictionary tomask.txt
-packageobfuscationdictionary tomask.txt
